"""Add PurchaseOrderCategoryOverride model

Revision ID: 100c4f875756
Revises: 80e9dbb8c556
Create Date: 2026-05-31 22:13:28.535951

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '100c4f875756'
down_revision = '80e9dbb8c556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_report_categories', schema=None) as batch_op:
        batch_op.drop_index('ix_purchase_report_categories_user_id')

    op.drop_table('purchase_report_categories')
    op.drop_table('nf_entry')
    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.alter_column('login_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('logout_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('purchase_item_nfe_matches', schema=None) as batch_op:
        batch_op.drop_index('ix_purchase_item_nfe_match_score')
        batch_op.create_index('ix_purchase_item_nfe_match_score', ['cod_pedc', 'cod_emp1', 'match_score'], unique=False)
        batch_op.drop_constraint('uq_purchase_item_nfe_match', type_='unique')
        batch_op.create_unique_constraint('uq_purchase_item_nfe_match', ['cod_pedc', 'cod_emp1', 'item_seq', 'nfe_item_id'])

    with op.batch_alter_table('purchase_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_items_cod_emp1'), ['cod_emp1'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_items_purchase_order_id'), ['purchase_order_id'], unique=False)

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_cod_emp1'), ['cod_emp1'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_fornecedor_id'), ['fornecedor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_func_nome'), ['func_nome'], unique=False)

    with op.batch_alter_table('request_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_term', sa.String(length=500), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'viewer'::character varying"))
        batch_op.alter_column('purchaser_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('allowed_screens',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
        batch_op.alter_column('session_token_created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('last_action_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('capabilities',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('data_filters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))

    with op.batch_alter_table('user_tokens', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('disabled_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.drop_index('idx_user_tokens_created_by_id')
        batch_op.drop_index('idx_user_tokens_disabled_by_id')
        batch_op.drop_index('idx_user_tokens_expires_at')
        batch_op.drop_index('idx_user_tokens_user_id')
        batch_op.drop_constraint('user_tokens_created_by_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('user_tokens_disabled_by_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('user_tokens_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['disabled_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['created_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_tokens_user_id_fkey', 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('user_tokens_disabled_by_id_fkey', 'user', ['disabled_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('user_tokens_created_by_id_fkey', 'user', ['created_by_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_index('idx_user_tokens_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_user_tokens_expires_at', ['expires_at'], unique=False)
        batch_op.create_index('idx_user_tokens_disabled_by_id', ['disabled_by_id'], unique=False)
        batch_op.create_index('idx_user_tokens_created_by_id', ['created_by_id'], unique=False)
        batch_op.alter_column('disabled_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('data_filters',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
        batch_op.alter_column('capabilities',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('last_action_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('session_token_created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('allowed_screens',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
        batch_op.alter_column('purchaser_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'viewer'::character varying"))

    with op.batch_alter_table('request_logs', schema=None) as batch_op:
        batch_op.drop_column('search_term')

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_func_nome'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_fornecedor_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_cod_emp1'))

    with op.batch_alter_table('purchase_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_items_purchase_order_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_items_cod_emp1'))

    with op.batch_alter_table('purchase_item_nfe_matches', schema=None) as batch_op:
        batch_op.drop_constraint('uq_purchase_item_nfe_match', type_='unique')
        batch_op.create_unique_constraint('uq_purchase_item_nfe_match', ['purchase_item_id', 'nfe_item_id'])
        batch_op.drop_index('ix_purchase_item_nfe_match_score')
        batch_op.create_index('ix_purchase_item_nfe_match_score', ['purchase_item_id', 'match_score'], unique=False)

    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.alter_column('logout_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('login_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    op.create_table('nf_entry',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cod_emp1', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('cod_pedc', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('linha', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('num_nf', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('text_field', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dt_ent', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('qtde', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='nf_entry_pkey')
    )
    op.create_table('purchase_report_categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='purchase_report_categories_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='purchase_report_categories_pkey'),
    sa.UniqueConstraint('user_id', 'category_name', name='uq_user_category')
    )
    with op.batch_alter_table('purchase_report_categories', schema=None) as batch_op:
        batch_op.create_index('ix_purchase_report_categories_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###
