"""add last_action_time to user

Revision ID: 2b82d9056a74
Revises: 22f4c0bd7387
Create Date: 2026-03-26 10:50:44.562840

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2b82d9056a74'
down_revision = '22f4c0bd7387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nf_entry')
    with op.batch_alter_table('purchase_item_nfe_matches', schema=None) as batch_op:
        batch_op.drop_index('ix_purchase_item_nfe_match_score')
        batch_op.create_index('ix_purchase_item_nfe_match_score', ['cod_pedc', 'cod_emp1', 'match_score'], unique=False)
        batch_op.drop_constraint('uq_purchase_item_nfe_match', type_='unique')
        batch_op.create_unique_constraint('uq_purchase_item_nfe_match', ['cod_pedc', 'cod_emp1', 'item_seq', 'nfe_item_id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_action_time', sa.DateTime(), nullable=True))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'viewer'::character varying"))
        batch_op.alter_column('purchaser_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('allowed_screens',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)

    with op.batch_alter_table('user_tokens', schema=None) as batch_op:
        batch_op.drop_index('idx_user_tokens_created_by_id')
        batch_op.drop_index('idx_user_tokens_disabled_by_id')
        batch_op.drop_index('idx_user_tokens_expires_at')
        batch_op.drop_index('idx_user_tokens_user_id')
        batch_op.drop_constraint('user_tokens_disabled_by_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('user_tokens_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('user_tokens_created_by_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['created_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['disabled_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_tokens_created_by_id_fkey', 'user', ['created_by_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key('user_tokens_user_id_fkey', 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('user_tokens_disabled_by_id_fkey', 'user', ['disabled_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index('idx_user_tokens_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_user_tokens_expires_at', ['expires_at'], unique=False)
        batch_op.create_index('idx_user_tokens_disabled_by_id', ['disabled_by_id'], unique=False)
        batch_op.create_index('idx_user_tokens_created_by_id', ['created_by_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('allowed_screens',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
        batch_op.alter_column('purchaser_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'viewer'::character varying"))
        batch_op.drop_column('last_action_time')

    with op.batch_alter_table('purchase_item_nfe_matches', schema=None) as batch_op:
        batch_op.drop_constraint('uq_purchase_item_nfe_match', type_='unique')
        batch_op.create_unique_constraint('uq_purchase_item_nfe_match', ['purchase_item_id', 'nfe_item_id'])
        batch_op.drop_index('ix_purchase_item_nfe_match_score')
        batch_op.create_index('ix_purchase_item_nfe_match_score', ['purchase_item_id', 'match_score'], unique=False)

    op.create_table('nf_entry',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cod_emp1', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('cod_pedc', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('linha', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('num_nf', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('text_field', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dt_ent', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('qtde', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='nf_entry_pkey')
    )
    # ### end Alembic commands ###
