"""timezone aware user and user token tables

Revision ID: 2eebc37c5fa0
Revises: dd7d68fcb172
Create Date: 2026-03-31 10:00:29.065451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eebc37c5fa0'
down_revision = 'dd7d68fcb172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nf_entry')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nf_entry',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cod_emp1', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('cod_pedc', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('linha', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('num_nf', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('text_field', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dt_ent', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('qtde', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='nf_entry_pkey')
    )
    # ### end Alembic commands ###
