"""Add PurchaseNFEMatch table

Revision ID: 582f606f02da
Revises: 
Create Date: 2025-11-28 16:38:36.601704

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '582f606f02da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nf_entry')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'viewer'::character varying"))
        batch_op.alter_column('purchaser_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('allowed_screens',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('allowed_screens',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
        batch_op.alter_column('purchaser_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'viewer'::character varying"))

    op.create_table('nf_entry',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cod_emp1', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('cod_pedc', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('linha', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('num_nf', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('text_field', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dt_ent', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('qtde', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='nf_entry_pkey')
    )
    # ### end Alembic commands ###
