"""Add PurchaseItemNFEMatch table

Revision ID: 613d19744f10
Revises: 582f606f02da
Create Date: 2025-11-28 17:08:22.904058

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '613d19744f10'
down_revision = '582f606f02da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_nfe_matches', schema=None) as batch_op:
        batch_op.drop_index('ix_purchase_nfe_match_score')
        batch_op.drop_index('ix_purchase_nfe_matches_cod_emp1')
        batch_op.drop_index('ix_purchase_nfe_matches_cod_pedc')
        batch_op.drop_index('ix_purchase_nfe_matches_nfe_chave')

    op.drop_table('purchase_nfe_matches')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_nfe_matches',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cod_pedc', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('cod_emp1', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('purchase_order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nfe_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nfe_chave', sa.VARCHAR(length=44), autoincrement=False, nullable=False),
    sa.Column('nfe_numero', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('match_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('match_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('is_combination', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('combination_nfes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('cnpj_match_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('item_match_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('value_match_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('po_reference_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('date_proximity_bonus', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('items_matched', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('items_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('value_coverage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('nfe_fornecedor', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('nfe_valor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('nfe_data_emissao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['nfe_id'], ['nfe_data.id'], name='purchase_nfe_matches_nfe_id_fkey'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name='purchase_nfe_matches_purchase_order_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='purchase_nfe_matches_pkey'),
    sa.UniqueConstraint('cod_pedc', 'cod_emp1', 'nfe_chave', name='uq_purchase_nfe_match')
    )
    with op.batch_alter_table('purchase_nfe_matches', schema=None) as batch_op:
        batch_op.create_index('ix_purchase_nfe_matches_nfe_chave', ['nfe_chave'], unique=False)
        batch_op.create_index('ix_purchase_nfe_matches_cod_pedc', ['cod_pedc'], unique=False)
        batch_op.create_index('ix_purchase_nfe_matches_cod_emp1', ['cod_emp1'], unique=False)
        batch_op.create_index('ix_purchase_nfe_match_score', ['cod_pedc', 'cod_emp1', 'match_score'], unique=False)

    # ### end Alembic commands ###
