"""Add user_id column to track who made the match

Revision ID: add_user_id_to_nfe_matches
Revises: d829e9273745
Create Date: 2025-01-08 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_user_id_to_nfe_matches'
down_revision = 'd829e9273745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_item_nfe_matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matched_by_user_id', sa.String(50), nullable=True, server_default='0000'))
        batch_op.add_column(sa.Column('match_type', sa.String(50), nullable=True, server_default='auto'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_item_nfe_matches', schema=None) as batch_op:
        batch_op.drop_column('matched_by_user_id')
        batch_op.drop_column('match_type')

    # ### end Alembic commands ###
