"""add search_term to request_logs

Revision ID: add_search_term
Revises: dd7d68fcb172
Create Date: 2026-05-21 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_search_term'
down_revision = 'dd7d68fcb172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_logs', sa.Column('search_term', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_logs', 'search_term')
    # ### end Alembic commands ###
