"""Make purchase_item_id nullable with SET NULL on delete

Revision ID: d829e9273745
Revises: 5db6f21eeb2c
Create Date: 2025-12-05 08:06:00.709790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd829e9273745'
down_revision = '5db6f21eeb2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_item_nfe_matches', schema=None) as batch_op:
        batch_op.alter_column('purchase_item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index('ix_purchase_item_nfe_match_score')
        batch_op.create_index('ix_purchase_item_nfe_match_score', ['cod_pedc', 'cod_emp1', 'match_score'], unique=False)
        batch_op.drop_constraint('uq_purchase_item_nfe_match', type_='unique')
        batch_op.create_unique_constraint('uq_purchase_item_nfe_match', ['cod_pedc', 'cod_emp1', 'item_seq', 'nfe_item_id'])
        batch_op.drop_constraint('purchase_item_nfe_matches_purchase_item_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'purchase_items', ['purchase_item_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_item_nfe_matches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('purchase_item_nfe_matches_purchase_item_id_fkey', 'purchase_items', ['purchase_item_id'], ['id'])
        batch_op.drop_constraint('uq_purchase_item_nfe_match', type_='unique')
        batch_op.create_unique_constraint('uq_purchase_item_nfe_match', ['purchase_item_id', 'nfe_item_id'])
        batch_op.drop_index('ix_purchase_item_nfe_match_score')
        batch_op.create_index('ix_purchase_item_nfe_match_score', ['purchase_item_id', 'match_score'], unique=False)
        batch_op.alter_column('purchase_item_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
