"""add capabilities and data filters to user

Revision ID: dd7d68fcb172
Revises: 2b82d9056a74
Create Date: 2026-03-26 16:24:31.324706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd7d68fcb172'
down_revision = '2b82d9056a74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capabilities', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('data_filters', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('data_filters')
        batch_op.drop_column('capabilities')

    # ### end Alembic commands ###
